// <auto-generated />
using System;
using Api_Almoxarifado_Mirvi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Almoxarifado_Mirvi.Migrations
{
    [DbContext(typeof(Api_Almoxarifado_MirviContext))]
    [Migration("20230519155116_AddOutrasEntidades")]
    partial class AddOutrasEntidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api_Almoxarifado_Mirvi.Models.Almoxarifado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Almoxarifado");
                });

            modelBuilder.Entity("Api_Almoxarifado_Mirvi.Models.Corredores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlmoxarifadoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AlmoxarifadoId");

                    b.ToTable("Corredores");
                });

            modelBuilder.Entity("Api_Almoxarifado_Mirvi.Models.Enderecos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PrateleirasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrateleirasId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Api_Almoxarifado_Mirvi.Models.Prateleiras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CorredoresId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubDivisoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CorredoresId");

                    b.ToTable("Prateleiras");
                });

            modelBuilder.Entity("Api_Almoxarifado_Mirvi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("C_STalisca")
                        .HasColumnType("longtext");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeCompra")
                        .HasColumnType("longtext");

                    b.Property<string>("Comprimento")
                        .HasColumnType("longtext");

                    b.Property<string>("Conexao")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Diametro")
                        .HasColumnType("longtext");

                    b.Property<int?>("EnderecosId")
                        .HasColumnType("int");

                    b.Property<string>("Fabricante")
                        .HasColumnType("longtext");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("longtext");

                    b.Property<string>("H225_H300")
                        .HasColumnType("longtext");

                    b.Property<string>("Hpn")
                        .HasColumnType("longtext");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<string>("Medida")
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .HasColumnType("longtext");

                    b.Property<int>("PrateleirasId")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasColumnType("longtext");

                    b.Property<string>("S_N")
                        .HasColumnType("longtext");

                    b.Property<string>("Uso")
                        .HasColumnType("longtext");

                    b.Property<string>("Valor")
                        .HasColumnType("longtext");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnderecosId");

                    b.HasIndex("PrateleirasId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Api_Almoxarifado_Mirvi.Models.Corredores", b =>
                {
                    b.HasOne("Api_Almoxarifado_Mirvi.Models.Almoxarifado", "Almoxarifado")
                        .WithMany("Corredores")
                        .HasForeignKey("AlmoxarifadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almoxarifado");
                });

            modelBuilder.Entity("Api_Almoxarifado_Mirvi.Models.Enderecos", b =>
                {
                    b.HasOne("Api_Almoxarifado_Mirvi.Models.Prateleiras", "Prateleiras")
                        .WithMany("Enderecos")
                        .HasForeignKey("PrateleirasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prateleiras");
                });

            modelBuilder.Entity("Api_Almoxarifado_Mirvi.Models.Prateleiras", b =>
                {
                    b.HasOne("Api_Almoxarifado_Mirvi.Models.Corredores", "Corredores")
                        .WithMany("Prateleiras")
                        .HasForeignKey("CorredoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corredores");
                });

            modelBuilder.Entity("Api_Almoxarifado_Mirvi.Models.Produto", b =>
                {
                    b.HasOne("Api_Almoxarifado_Mirvi.Models.Enderecos", "Enderecos")
                        .WithMany("Produto")
                        .HasForeignKey("EnderecosId");

                    b.HasOne("Api_Almoxarifado_Mirvi.Models.Prateleiras", "Prateleiras")
                        .WithMany("Produto")
                        .HasForeignKey("PrateleirasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enderecos");

                    b.Navigation("Prateleiras");
                });

            modelBuilder.Entity("Api_Almoxarifado_Mirvi.Models.Almoxarifado", b =>
                {
                    b.Navigation("Corredores");
                });

            modelBuilder.Entity("Api_Almoxarifado_Mirvi.Models.Corredores", b =>
                {
                    b.Navigation("Prateleiras");
                });

            modelBuilder.Entity("Api_Almoxarifado_Mirvi.Models.Enderecos", b =>
                {
                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Api_Almoxarifado_Mirvi.Models.Prateleiras", b =>
                {
                    b.Navigation("Enderecos");

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
